# Generated by Django 4.0.4 on 2022-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='jam',
            field=models.CharField(default='Jam 8', max_length=100),
            preserve_default=False,
        ),
    ]
